### ISSUE TITLE
Question : Using consumer as uuid

### ISSUE THREAD

**Issue by KIMBEOBWOO** [tamimaj/nestjs-redis-streams#21]
When there is a horizontally expanding Receiver nestjs app (at least two), the consumer group can be set to the same string, but the consumer identifier should not be set to the same value.
(Because the official document said it was an identifier that identified consumers within the group.)

So I'm trying to deliver the consumer value at the time the server turns on with the UUID value, is it okay to use it like this?

**Comment by tamimaj** [comment]
Hey @KIMBEOBWOO, of course. For a cluster of receiver services. You should do the following.

Consumer Group: "users", which mean all the users instances.
Current Consumer Name: "users-1", "users-2", "users-3", each service should have a different consumer name, when redis needs to send a message to a consumer group, it sends it to one of those consumer, and if it fails or it is down, will send it to another one, because they all belong to the same group.

Using UUID, would work is just a string, but I prefer to use more descriptive strings, api-gateway-1 users-1, notifications-2, etc
